# LiDARs projection parameters
- name: HDL-32
  params:
    vertical_span:
      start_angle: 10
      end_angle: -30
      step: 1.25
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.4137931
- name: HDL-64
  params:
    vertical_span:
      start_angle: 2
      end_angle: -24.87
      step: 0.4198438
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.4137931
- name: OS-1-16-0512
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 2.075
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.703125
- name: OS-1-16-1024
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 2.075
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.3515625
- name: OS-1-16-2048
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 2.075
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.1757812
- name: OS-1-64-0512
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 0.51875
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.703125
- name: OS-1-64-1024
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 0.51875
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.3515625
- name: OS-1-64-2048
  params:
    vertical_span:
      start_angle: 16.6
      end_angle: -16.6
      step: 0.51875
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.1757812
- name: VLP-16
  params:
    vertical_span:
      start_angle: 15
      end_angle: -15
      step: 1.875
    horizontal_span:
      start_angle: -180
      end_angle: 180
      step: 0.4137931