/watchdog_node:
  node_number: 0
  errors:
  - num: 0
    name: required file does not exist
    category: 7    
    description: required file does not exist
/decision_maker_node:
  node_number: 0
  errors:
  - num: 0
    name:  out of range
    category: 8    
    description: The input value hogehoge is out of range.
  - num: 1
    name:  node is ded
    category: 3    
    description: /pure_pursuit node is dead