language: generic
services:
  - docker
env:
  matrix:
    - ROS_DISTRO="melodic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true' BUILDER=colcon ROSINSTALL_FILENAME=autoware.repos UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true' ROSINSTALL_FILENAME=autoware.repos UPSTREAM_WORKSPACE=file

install:
  - git clone --branch colcon --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
